package mandala

import (
	"unsafe"

	"git.tideland.biz/goas/loop"
)

type LoadAssetResponse struct {
	// The buffer containing the resource. Please note that, in
	// case io.Reader is os.File, it's a client code
	// responsibility to close it. This usually happens in the
	// xorg version of your program. Maybe this API will change in
	// the future, though.
	Buffer []byte

	// The error eventually generated by the reading operation.
	Error error
}

// The type of request to send to AssetManager in order to read the
// resource.
type LoadAssetRequest struct {
	// The path of the resource file, for example
	// "res/drawable/gopher.png". AssetPath will be prefixed to
	// Filename.
	Filename string

	// Response is a channel for receiving the response from the
	// asset manager.
	Response chan LoadAssetResponse
}

// Run runs the nativeEventsLoop.
// The loop handles native input events.
func assetLoopFunc(activity chan unsafe.Pointer, request chan interface{}) loop.LoopFunc {
	var act unsafe.Pointer
	return func(l loop.Loop) error {
		for {
			select {
			case act = <-activity:
			case untypedRequest := <-request:
				switch req := untypedRequest.(type) {
				case LoadAssetRequest:
					buf, err := loadAsset(act, req.Filename)
					req.Response <- LoadAssetResponse{buf, err}
				}
			}
		}
	}
}

func ReadResource(filename string, responseCh chan LoadAssetResponse) {
	request := LoadAssetRequest{
		Filename: filename,
		Response: responseCh,
	}
	AssetManager() <- request
}
